// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PATHServer.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20221215113600_DataLiveModel")]
    partial class DataLiveModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("PATHServer.BDD.Models.ActionHistory", b =>
                {
                    b.Property<int>("ah_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("act_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ah_date")
                        .HasColumnType("TEXT");

                    b.Property<int>("ahi_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("pu_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("ah_id");

                    b.ToTable("ActionHistories");
                });

            modelBuilder.Entity("PATHServer.BDD.Models.ActionHistoryInfo", b =>
                {
                    b.Property<int>("ahi_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ahi_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("ahi_id");

                    b.ToTable("ActionHistoryInfos");
                });

            modelBuilder.Entity("PATHServer.BDD.Models.ActionTrigger", b =>
                {
                    b.Property<int>("act_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("act_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("act_type_data")
                        .HasColumnType("INTEGER");

                    b.HasKey("act_id");

                    b.ToTable("ActionTriggers");
                });

            modelBuilder.Entity("PATHServer.BDD.Models.DataHistory", b =>
                {
                    b.Property<int>("dh_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dh_date")
                        .HasColumnType("TEXT");

                    b.Property<int>("node_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("dh_id");

                    b.ToTable("DataHistories");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DataHistory");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PATHServer.BDD.Models.DataLive", b =>
                {
                    b.Property<int>("dl_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("dl_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dl_val_datetime")
                        .HasColumnType("TEXT");

                    b.Property<float>("dl_val_double")
                        .HasColumnType("REAL");

                    b.Property<string>("dl_val_int")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dl_val_string")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("dl_id");

                    b.ToTable("DataLives");
                });

            modelBuilder.Entity("PATHServer.BDD.Models.KeyConnexion", b =>
                {
                    b.Property<string>("key_id")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("key_created")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("key_lastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("key_quota")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("key_quotaRefresh")
                        .HasColumnType("TEXT");

                    b.Property<int>("pu_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("key_id");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("PATHServer.BDD.Models.Log", b =>
                {
                    b.Property<string>("log_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("log_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("log_what")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("log_when")
                        .HasColumnType("TEXT");

                    b.Property<int?>("log_who")
                        .HasColumnType("INTEGER");

                    b.HasKey("log_id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("PATHServer.BDD.Models.Node", b =>
                {
                    b.Property<int>("node_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("node_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("node_type_data")
                        .HasColumnType("INTEGER");

                    b.HasKey("node_id");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("PATHServer.BDD.Models.PATHUser", b =>
                {
                    b.Property<int>("pu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("pu_admin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("pu_email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("pu_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("pu_password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("pu_surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("pu_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PATHServer.BDD.Models.DataHistoryBool", b =>
                {
                    b.HasBaseType("PATHServer.BDD.Models.DataHistory");

                    b.Property<bool>("dh_bool_value")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("DataHistoryBool");
                });

            modelBuilder.Entity("PATHServer.BDD.Models.DataHistoryDate", b =>
                {
                    b.HasBaseType("PATHServer.BDD.Models.DataHistory");

                    b.Property<DateTime>("dh_date_value")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("DataHistoryDate");
                });

            modelBuilder.Entity("PATHServer.BDD.Models.DataHistoryDouble", b =>
                {
                    b.HasBaseType("PATHServer.BDD.Models.DataHistory");

                    b.Property<double>("dh_double_value")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("DataHistoryDouble");
                });

            modelBuilder.Entity("PATHServer.BDD.Models.DataHistoryInt", b =>
                {
                    b.HasBaseType("PATHServer.BDD.Models.DataHistory");

                    b.Property<int>("dh_int_value")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("DataHistoryInt");
                });

            modelBuilder.Entity("PATHServer.BDD.Models.DataHistoryString", b =>
                {
                    b.HasBaseType("PATHServer.BDD.Models.DataHistory");

                    b.Property<string>("dh_string_value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("DataHistoryString");
                });
#pragma warning restore 612, 618
        }
    }
}
