<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="CommandEnv\Class1.cs" />
    <Compile Remove="CommandEnv\Class2.cs" />
    <Compile Remove="CommandEnv\Class3.cs" />
    <Compile Remove="CommandEnv\Cmd.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.0" />
    <PackageReference Include="Microsoft.Graph" Version="4.48.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Socket\Socket.csproj" />
  </ItemGroup>

</Project>
